version: '3.8'
services:
  istad_lms_api:
    container_name: 'istad_lms_front'
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      - TZ=Asia/Bangkok
    ports:
      - '7777:8080'
    volumes:
      - '/home/istad_lms/images:/home/istad/media'
