spring:
#  main:
#    allow-circular-references: true
  application:
    name: online_survey
#  servlet: # this is for file upload
#    multipart:
#      max-file-size: 100MB
#      max-request-size: 500MB
  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: oracle.jdbc.OracleDriver
#    url: jdbc:oracle:thin:@localhost:1521/orc
    url: jdbc:oracle:thin:@${DB_HOST}:${DB_PORT}/${DB_NAME}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    generate-ddl: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.OracleDialect
  #  security:
  #    user:
  #      name: ${SECURITY_NAME}
  #      password: ${SECURITY_PASSWORD}
  #  mail:
  #    username: ${MAIL_USERNAME}
  #    password: ${MAIL_PASSWORD}
  #    host: ${MAIL_HOST}
  #    port: ${MAIL_HOST_PORT}
  #    properties:
  #      mail:
  #        smtp:
  #          auth: true
  #        starttls:
  #          enable: true
  profiles:
    active: dev